version: '3.4'

services:
  event_store:
    #image: eventstore/eventstore:release-5.0.11
    image: eventstore/eventstore:21.6.0-buster-slim
    restart: always
    environment:
      EVENTSTORE_RUN_PROJECTIONS: "All"
      EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
      EVENTSTORE_CLUSTER_SIZE: 1
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_INSECURE: "true"
      EVENTSTORE_ENABLE_EXTERNAL_TCP: "true"
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"
    ports:
      - 1113:1113
      - 2113:2113
    volumes:
      - ./volumes/eventstore/data:/var/lib/eventstore
      - ./volumes/eventstore/log:/var/log/eventstore
